# # Stage 1: Build
# FROM node:18-alpine AS builder

# # Set working directory
# WORKDIR /app

# # Copy package.json and package-lock.json
# COPY package*.json ./

# # Install dependencies
# RUN npm ci

# # Copy the rest of the application
# COPY . .

# # Build the NestJS application
# RUN npm run build

# # Stage 2: Production image
# FROM node:18-alpine

# WORKDIR /app

# # Copy package.json and package-lock.json for production dependencies
# COPY package*.json ./

# # Install only production dependencies
# RUN npm ci --only=production

# # Copy built files from builder stage
# COPY --from=builder /app/dist ./dist
# COPY --from=builder /app/.env ./

# # Expose the port your app runs on
# EXPOSE 3000

# # Set environment variables
# ENV NODE_ENV=production

# # Run the application
# CMD ["node", "dist/main.js"]


# Stage 1: build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: production
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY package*.json ./
RUN npm install --production

EXPOSE 3000
CMD ["node", "dist/main.js"]